version: "3.3"
services:
    orion:
      image: fiware/orion-ld
      hostname: orion
      container_name: fiware-orion
      depends_on:
          - mongo-db
      ports:
          - "1026:1026"
      command: -dbhost mongo-db -logLevel DEBUG
  
    mongo-db:
      image: mongo:3.6
      hostname: mongo-db
      container_name: db-mongo
      expose:
          - "27017"
      ports:
          - "27017:27017"
      command: --nojournal

    deployer:
        build: .
        hostname: deployer
        container_name: deployer
        ports:
            - "8080:8080"
            - "3000:3000"
        environment:
            - GENESIS=http://192.168.1.41

    #genesis-light:
    #    image: nicolasferry/genesis-light
    #    hostname: genesis-light
    #    container_name: genesis-light
    #    ports:
    #        - "8880:8880"
    #        - "8000:8000"
    #        - "9001:9001"
